=== diegmonti/ifttt-clone/src/main/resources/wro.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.isdc.ro/wro" xmlns="http://www.isdc.ro/wro"
	elementFormDefault="qualified">

	<xsd:element name="groups" type="Groups" />

	<xsd:complexType name="Groups">
		<xsd:choice minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="import" type="xsd:string" />
			<xsd:element name="group" type="Group" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="Group">
		<xsd:choice minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="css">
				<xsd:complexType mixed="true">
					<xsd:attribute name="minimize" type="xsd:boolean"
						use="optional" default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="js">
				<xsd:complexType mixed="true">
					<xsd:attribute name="minimize" type="xsd:boolean"
						use="optional" default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="group-ref" type="xsd:IDREF" />
		</xsd:choice>
		<xsd:attribute name="name" type="xsd:ID" use="required" />
	</xsd:complexType>

</xsd:schema>

=== diegmonti/ifttt-clone/src/main/resources/wro/wro.xml
<?xml version="1.0" encoding="UTF-8"?>
<groups xmlns="http://www.isdc.ro/wro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.isdc.ro/wro wro.xsd">
	<group name="bootstrap">
		<js>webjar:bootstrap/3.3.6/js/bootstrap.min.js</js>
		<css>webjar:bootstrap/3.3.6/css/bootstrap.min.css</css>
	</group>
	<group name="jquery">
		<js>webjar:jquery/2.2.3/jquery.js</js>
	</group>
	<group name="angular">
		<js>webjar:angularjs/1.5.5/angular.js</js>
		<js>webjar:angularjs/1.5.5/angular-route.js</js>
	</group>
</groups>

=== diegmonti/ifttt-clone/src/main/resources/wro.xml
<?xml version="1.0" encoding="UTF-8"?>
<groups xmlns="http://www.isdc.ro/wro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.isdc.ro/wro wro.xsd">
	<group name="lib">
		<js>webjar:jquery/2.2.3/jquery.js</js>
		<js>webjar:tether/1.3.2/dist/js/tether.min.js</js>
		<js>webjar:bootstrap/4.0.0-alpha.2/js/bootstrap.min.js</js>
		<js>webjar:angularjs/1.5.5/angular.js</js>
		<js>webjar:angularjs/1.5.5/angular-route.js</js>
		<js>webjar:angularjs/1.5.5/angular-resource.js</js>
		<js>webjar:momentjs/2.13.0/min/moment.min.js</js>

		<css>webjar:tether/1.3.2/dist/css/tether.min.css</css>
		<css>webjar:bootstrap/4.0.0-alpha.2/css/bootstrap.min.css</css>
		<css>classpath:META-INF/resources/webjars/font-awesome/4.6.3/css/font-awesome.min.css</css>
	</group>
	<group name="app">
		<js>/WEB-INF/js/app.js</js>
		<js>/WEB-INF/js/controllers/**</js>
	</group>
</groups>
